language: node_js
node_js:
  - "0.10"
services:
  - mongodb
install:
  # Install gmsmith dependencies
  - wget http://sourceforge.net/projects/graphicsmagick/files/graphicsmagick/1.3.17/GraphicsMagick-1.3.17.tar.xz/download --output-document GraphicsMagick-1.3.17.tar.xz
  - tar xvf GraphicsMagick-1.3.17.tar.xz
  - cd GraphicsMagick-1.3.17
  - ./configure
  - make
  - sudo make install
  - cd ..
  # Install node modules
  - make install